name: mist-statinf
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - appnope=0.1.4=py311hca03da5_0
  - asttokens=3.0.0=py311hca03da5_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.9.9=hca03da5_0
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.11.14=py311hd8ed1ab_2
  - debugpy=1.8.16=py311h50f4ffc_1
  - decorator=5.2.1=py311hca03da5_0
  - exceptiongroup=1.3.0=py311hca03da5_0
  - executing=2.2.1=py311hca03da5_0
  - expat=2.7.1=h313beb8_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=py311hca03da5_0
  - ipython=9.5.0=py311hca03da5_0
  - ipython_pygments_lexers=1.1.1=py311hca03da5_0
  - jedi=0.19.2=py311hca03da5_0
  - jupyter_client=8.6.3=py311hca03da5_0
  - jupyter_core=5.8.1=py311hca03da5_0
  - krb5=1.21.3=h95cc1b6_4
  - libcxx=20.1.8=hd7fd590_1
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libffi=3.4.4=hca03da5_1
  - libkrb5=1.21.3=h73ed823_4
  - libmpdec=4.0.0=h80987f9_0
  - libsodium=1.0.20=h897f8a9_0
  - lmdb=0.9.31=h79febb2_0
  - matplotlib-inline=0.1.7=py311hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py311hca03da5_0
  - openssl=3.5.2=he92f556_0
  - packaging=25.0=py311hca03da5_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=py311hca03da5_1
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=25.2=pyhc872135_1
  - platformdirs=4.4.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=py311hca03da5_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py311haa24f5a_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py311hca03da5_0
  - pygments=2.19.2=py311hca03da5_0
  - python=3.11.14=hf701271_0
  - python-dateutil=2.9.0.post0=py311hca03da5_1
  - python-gil=3.11.14=hd8ed1ab_2
  - python_abi=3.11=2_cp311
  - pyzmq=27.1.0=py311h5a8c52c_1
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - six=1.17.0=py311hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - stack_data=0.6.3=py311hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.1=py311h80987f9_0
  - traitlets=5.14.3=py311hca03da5_0
  - typing-extensions=4.15.0=py311hca03da5_0
  - typing_extensions=4.15.0=py311hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - wcwidth=0.2.13=py311hca03da5_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h2c7f8f0_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=ha1e9f54_2
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - alembic==1.17.1
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - attrs==25.4.0
      - benchmark-mi==0.1.3
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - chex==0.1.90
      - cloudpickle==3.1.1
      - colorlog==6.10.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==4.2.0
      - dill==0.4.0
      - dm-tree==0.1.9
      - equinox==0.10.11
      - filelock==3.20.0
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gast==0.6.0
      - h11==0.16.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - idna==3.11
      - jax==0.4.33
      - jaxlib==0.4.33
      - jaxtyping==0.3.3
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonlines==4.0.0
      - kiwisolver==1.4.9
      - lightning-utilities==0.15.2
      - mako==1.3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - networkx==3.5
      - numpy==1.26.4
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - optax==0.1.9
      - optuna==4.6.0
      - pandas==1.5.3
      - pillow==12.0.0
      - propcache==0.4.1
      - pyarrow==21.0.0
      - pydantic==1.10.24
      - pyparsing==3.2.5
      - pytorch-lightning==2.5.5
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - seaborn==0.13.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - sympy==1.14.0
      - tensorflow-probability==0.20.1
      - threadpoolctl==3.6.0
      - toolz==1.1.0
      - torch==2.9.0
      - torchmetrics==1.8.2
      - torchvision==0.24.0
      - tqdm==4.67.1
      - urllib3==2.5.0
      - wadler-lindig==0.1.7
      - wrapt==2.0.0
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /opt/miniconda3/envs/test_env